
POST http://localhost:3000/transactions
Content-Type: application/json

{
	"description":"JhonatanAQ",
	"valueMoney":5,
	"recordsInAndOut":"recordsInAndOut",
	"category":"category",
	"targetDate":"09/12/2000",
    "paymentMethod":"paymentMethod"
}
###
GET http://localhost:3000/transactions

###
DELETE http://localhost:3000/transactions/12